object Compose {
    const val composeVersion = "1.2.1"
    private const val composeUITooling = "1.2.1"
    const val composeCompilerVersion = "1.1.1"
    private const val navigationVersion = "2.4.0-beta02"
    private const val hiltNavigationComposeVersion = "1.0.0-beta01"
    private const val activityComposeVersion = "1.4.0"
    private const val lifecycleVersion = "2.4.0"

    const val ui = "androidx.compose.ui:ui:$composeVersion"
    const val uiToolingPreview="androidx.compose.ui:ui-tooling-preview:$composeVersion"
    const val material="androidx.compose.material:material:$composeVersion"
    const val runtime = "androidx.compose.runtime:runtime:$composeVersion"
    const val compiler = "androidx.compose.compiler:compiler:$composeCompilerVersion"
    const val navigation = "androidx.navigation:navigation-compose:$navigationVersion"
    const val hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:$hiltNavigationComposeVersion"
    const val activityCompose = "androidx.activity:activity-compose:$activityComposeVersion"
    const val viewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycleVersion"
    const val composeUnitTest="androidx.compose.ui:ui-test-junit4:$composeUITooling"
    const val composeDebugTest="androidx.compose.ui:ui-tooling:$composeUITooling"
    const val composeDebugTestManifest="androidx.compose.ui:ui-test-manifest:$composeUITooling"
}